config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'
  resources :users
  resources :books
  resources :reservations

  resources :events

  # POST   '/books/book_id/reservations(:format)'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :reservations
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :book


  def date_before_start
    errors.add(:start_date, "は過去の日付を選択できません") if start_date < Date.today
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :reservations, dependent: :destroy
  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
     @books = Book.all
     @book = Book.new
     @user = current_user
     @events = Event.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @user = current_user
    if @book.save
      flash[:notice] = 'You have created book successfully.'
      redirect_to books_path
    else
      @books = Book.all
      render 'index'
    end
  end

  private
    def book_params
      params.require(:book).permit(:title, :body, :user_id)
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def new
    @event = Event.new

  def create
    @event = Event.new(event_params)
    @event.save
    redirect_to books_path
    @events = Event.where(user_id: current_user.id)
  end

  def update
    event = Event.find(params[:id])
    @events = Event.where(user_id: current_user.id)
    event.update(event_params)
  end

  def destroy
    @user = User.find(params[:id])
    event = Event.find(params[:id])
    event.destroy
    redirect_to user_path(@user)
  end

  private
  def event_params
    params.require(:event).permit(:title, :start, :end, :user_id, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def index
    @reservations = Reservation.all
  end

  def new
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.save
    redirect_to books_path
    # @reservation = current_user.reservations.create(reservation_params)
    # redirect_to books_path notice:"予約が完了しました"
　end

  private
  def reservation_
    params.require(:reservation).permit(:title, :start_date, :end_date, :book_id)
  end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @book = @user.books
    @events = Event.where(user_id: @user.id)
    @event = Event.new
  end

  def create
    @user = User.new(user_params)
    @user.user_id = current_user.id
    if @user.save
      flash[:notice] = "You have save user successfully."
      redirect_to books_path
    else
       flash.now[:notice] = "You have user error successfully."
      render :index
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>Events#index</h1>
<%= month_calendar events: @events do |date, events| %>
  <%= date.day %>
<% end %>
<%= link_to 'イベント追加', new_event_path, class: "btn btn-danger mt-5" %>

app/views/events/new.html.erb
<%= form_with(model: @event, local: true) do |form| %>

  <div class="title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

    <div class="time">
    <%= form.label :start %>
    <%= form.datetime_select :start %>
  </div>

  <div class="content">
    <%= form.label :end %>
    <%= form.datetime_select :end %>
  </div>


  <div class="submit">
    <%= form.submit %>
  </div>

<% end %>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-1 mt-5">
      <h2>あなたが投稿したもの</h2>
        <table class="table mt-3">
          <thead>
            <tr>
              <th>Title</th>
              <th>opinion</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <% @book.each do |book| %>
              <td><%= book.title %></td>
              <td><%= book.body %></td>
            </tr>
          </tbody>
          <% end %>
        </table>
    </div>
    <h3 class="text-center">カレンダー</h3>
    <!-- カレンダーの表示 -->
    <div id="calendar"></div>
    <!-- もしユーザーがログインしていたら -->
    <% if user_signed_in? %>
    <!-- ページのparams.idがログインユーザー.idと同じなら -->
    <% if @user.id == current_user.id %>
        <div id="inputScheduleForm" class="modal fade" tabindex="-1">
            <div class="modal-dialog modal-nm">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">スケジュール登録</h4>
                    </div>
                    <div class="modal-body">
                        <%= form_with model: @event, local:true do |f| %>
                          <div  class="col">
                            <p>
                              <span>タイトル</span>
                              <span><%= f.text_field :title, class: "form-control", placeholder: "タイトルを入力してください" %></span>
                            </p>
                              <span>開始日時</span>
                              <span><%= f.datetime_field  :start, placeholder: "XXXX-XX-XX", class:"field" %> ~ </span><br>
                              <span>終了日時</span>
                              <span><%= f.datetime_field :end, placeholder: "XXXX-XX-XX", class:"field" %></span><br>
                              <span>詳細
                              <%= f.text_field :body, class: "form-control", placeholder: "タイトルの詳細を記入してください" %></span>
                          </div>
                          <div class="modal-footer">
                            <%= f.submit "登録する", class: "btn btn-primary" %>
                            <%= f.hidden_field :user_id, :value => current_user.id %>
                            <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
                          </div>
                      <% end %>
                  </div>
                </div>
            </div>
        </div>
<!-- 編集 ------------------------------------------------------------------>
        <div id="inputEditForm">
            <%= render 'events/edit', events: @events %>
        </div>
    <% end %>
<% end %>
    <script>
    // CRUDを行う際にCSRF対策のtokenを発行
        $(document).ready(function() {
        var prepare = function(options, originalOptions, jqXHR) {
          var token;
          if (!options.crossDomain) {
            token = $('meta[name="csrf-token"]').attr('content');
            if (token) {
              return jqXHR.setRequestHeader('X-CSRF-Token', token);
            }
          }
        };
        }
        )

        // カレンダー表示
        $('#calendar').fullCalendar ({
            header: {
                left: 'prev,next today',
                center: 'month,agendaWeek,agendaDay',
                right: 'title'
            },

            buttonText: {
                  prev: "<",
                  next: ">"
            },

            timezone: 'UTC',
            events: '/users/events.json',
            navLinks: true,
            selectable: true,
            selectHelper: true,
            // 日付クリック
            dayClick : function ( date , jsEvent , view ) {
                $('#inputScheduleForm').modal('show');
                },

            // event クリックで編集、削除
            eventClick : function(event, jsEvent , view) {
                jsEvent.preventDefault();
                $(`#inputScheduleEditForm${event.id}`).modal('show');
            },

            eventMouseover : function(event, jsEvent , view) {
                jsEvent.preventDefault();
            }
        })

    </script>
  </div>
</div>